name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.28.1
  - pip=22.3
  - mlflow=2.2.2
  - hydra-core=1.0.6
  - pip:
    - wandb==0.13.4
    - hydra-joblib-launcher==1.1.2
